language: php
php:
  - 5.5
  - 5.4
  - 5.3
install: composer install --dev --no-interaction
script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml
after_script:
 - php vendor/bin/coveralls -v
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml